#!/bin/bash
# One-command deployment of Nightwatch to AWS.
# Usage: bash scripts/aws/deploy-all.sh
#
# Deploys: ECS + Lambda + DynamoDB + SNS (CDK), then Bedrock Agent + Knowledge Base.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=========================================="
echo "  NIGHTWATCH — FULL AWS DEPLOYMENT"
echo "=========================================="
echo ""

# Step 0: Environment check
echo ">>> Step 0: Checking AWS environment..."
bash "$SCRIPT_DIR/00-check-env.sh"
echo ""

# Step 1: Build and deploy CDK stack (ECS, Lambda, DynamoDB, SNS, CloudWatch)
echo ">>> Step 1: Deploying infrastructure (CDK)..."
cd "$ROOT/infra"
npx cdk bootstrap 2>/dev/null || true
npx cdk deploy NightwatchRealStack --require-approval never --outputs-file "$ROOT/cdk-outputs.json"
cd "$ROOT"
echo ""

# Step 2: Extract outputs and write .env.demo
echo ">>> Step 2: Extracting stack outputs..."
TOOL_LAMBDA_ARN=$(node -e "const o=require('./cdk-outputs.json');console.log(o.NightwatchRealStack.ToolLambdaArn)")
TRIGGER_LAMBDA_ARN=$(node -e "const o=require('./cdk-outputs.json');console.log(o.NightwatchRealStack.TriggerLambdaArn)")
REGION=$(aws configure get region || echo "us-east-1")

cat > "$ROOT/.env.demo" <<EOF
# Generated by deploy-all.sh — DO NOT COMMIT
AWS_REGION=$REGION
FUNCTION_ARN=$TOOL_LAMBDA_ARN
TRIGGER_LAMBDA_ARN=$TRIGGER_LAMBDA_ARN
EOF
echo "  Saved to .env.demo"
echo ""

# Step 3: Create Bedrock Agent
echo ">>> Step 3: Creating Bedrock Agent with action groups..."
node "$SCRIPT_DIR/03-create-bedrock-agent.mjs"
echo ""

# Step 4: Create Knowledge Base
echo ">>> Step 4: Creating Knowledge Base..."
node "$SCRIPT_DIR/04-create-knowledge-base.mjs"
echo ""

# Step 5: Update Trigger Lambda with Bedrock Agent IDs
echo ">>> Step 5: Updating Trigger Lambda environment..."
source "$ROOT/.env.demo"
aws lambda update-function-configuration \
  --function-name nightwatch-trigger \
  --environment "Variables={BEDROCK_AGENT_ID=$BEDROCK_AGENT_ID,BEDROCK_AGENT_ALIAS_ID=$BEDROCK_AGENT_ALIAS_ID,INVESTIGATION_TABLE=nightwatch-investigations,SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}}" \
  --region "$REGION" > /dev/null
echo "  Trigger Lambda updated with Bedrock Agent IDs."
echo ""

echo "=========================================="
echo "  DEPLOYMENT COMPLETE"
echo "=========================================="
echo ""
echo "Resources created:"
echo "  - CDK Stack: NightwatchRealStack (VPC, ECS, Lambda, DynamoDB, SNS, CloudWatch)"
echo "  - Bedrock Agent: $BEDROCK_AGENT_ID"
echo "  - Knowledge Base (if created)"
echo ""
echo "All IDs saved to: .env.demo"
echo ""
echo "To trigger an incident (after getting the task IP):"
echo "  curl -X POST \"http://<TASK_IP>:3000/chaos/enable?mode=db-pool\" -H \"Authorization: Bearer chaos-secret\""
echo ""
echo "To tear down all resources:"
echo "  bash scripts/aws/teardown.sh"
